/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaggleRouteImport } from './routes/waggle'
import { Route as TeammatesRouteImport } from './routes/teammates'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsTabRouteImport } from './routes/settings.$tab'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'

const WaggleRoute = WaggleRouteImport.update({
  id: '/waggle',
  path: '/waggle',
  getParentRoute: () => rootRouteImport,
} as any)
const TeammatesRoute = TeammatesRouteImport.update({
  id: '/teammates',
  path: '/teammates',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsTabRoute = SettingsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => SettingsRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/teammates': typeof TeammatesRoute
  '/waggle': typeof WaggleRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/skills': typeof SkillsRoute
  '/teammates': typeof TeammatesRoute
  '/waggle': typeof WaggleRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/teammates': typeof TeammatesRoute
  '/waggle': typeof WaggleRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/_chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/settings'
    | '/skills'
    | '/teammates'
    | '/waggle'
    | '/sessions/$sessionId'
    | '/settings/$tab'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/skills'
    | '/teammates'
    | '/waggle'
    | '/sessions/$sessionId'
    | '/settings/$tab'
    | '/'
    | '/settings'
  id:
    | '__root__'
    | '/_chat'
    | '/mcp'
    | '/settings'
    | '/skills'
    | '/teammates'
    | '/waggle'
    | '/sessions/$sessionId'
    | '/settings/$tab'
    | '/_chat/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  McpRoute: typeof McpRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
  TeammatesRoute: typeof TeammatesRoute
  WaggleRoute: typeof WaggleRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waggle': {
      id: '/waggle'
      path: '/waggle'
      fullPath: '/waggle'
      preLoaderRoute: typeof WaggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teammates': {
      id: '/teammates'
      path: '/teammates'
      fullPath: '/teammates'
      preLoaderRoute: typeof TeammatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/$tab': {
      id: '/settings/$tab'
      path: '/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof SettingsTabRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsTabRoute: typeof SettingsTabRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsTabRoute: SettingsTabRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  McpRoute: McpRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsRoute: SkillsRoute,
  TeammatesRoute: TeammatesRoute,
  WaggleRoute: WaggleRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
